AWSTemplateFormatVersion: '2010-09-09'
Description: "Update Pluto with published information from CAPI"
Parameters:
  CapiStreamArn:
    Type: String
    Description: Arn of the Crier kinesis stream to attach to
  CapiStreamName:
    Type: String
    Description: Name of the Crier kinesis stream to attach to
  CapiRole:
    Type: String
    Description: ARN of the role to assume to read from the kinesis stream
  Mode:
    Type: String
    AllowedValues:
      - preview
      - live
    Description: Which CAPI mode to listen to
  PlutoHost:
    Type: String
    Description: Host or loadbalancer where pluto can be reached
  PlutoVidispinePort:
    Type: Number
    Description: Port on which Vidispine can be reached for Pluto
    Default: 8080
  PlutoUser:
    Type: String
    Description: Username to use to communicate
  PlutoPass:
    Type: String
    Description: Password to communicate
    NoEcho: true
  App:
    Type: String
    Description: Application identifier for RiffRaff
    Default: launchdetector
  Stack:
    Type: String
    Description: Stack identifier for RiffRaff
    Default: multimedia
  Stage:
    Type: String
    AllowedValues:
      - CODE
      - DEV
      - PROD
    Description: Deployment stage
  AmiId:
    Type: String
    Description: ID of the base image to build instances from.  Build this with Amigo.
  OfficeIpRange:
    Type: String
    Description: CIDR block of ip addresses to be allowed SSH access
  InstanceType:
    Type: String
    Description: What type of instance to launch
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    Default: t2.nano
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Root access keypair
  VPCID:
    Description: Virtual Private Cloud to deploy into
    Type: AWS::EC2::VPC::Id
  DeploySubnets:
    Description: Subnets to deploy into.  These should be the same as where the database lives.
    Type: List<AWS::EC2::Subnet::Id>
  NewRelicLicense:
    Description: License ID for New Relic
    Type: String
Resources:
  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Load-balancer security group for launchdetector
      SecurityGroupIngress:
        - CidrIp: !Ref OfficeIpRange
          FromPort: 9000
          ToPort: 9000
          IpProtocol: tcp
      VpcId: !Ref VPCID
  LoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      CrossZone: true
      HealthCheck:
        HealthyThreshold: "3"
        Interval: "10"
        Target: "HTTP:9000/is-online"
        Timeout: "3"
        UnhealthyThreshold: "2"
      Listeners:
        - InstancePort: "9000"
          InstanceProtocol: "http"
          LoadBalancerPort: "80"
          Protocol: "http"
      Scheme: internal
      SecurityGroups:
      - !GetAtt LoadBalancerSG.GroupId
      Subnets: !Ref DeploySubnets
      Tags:
      - Key: App
        Value: !Ref App
      - Key: Stack
        Value: !Ref Stack
      - Key: Stage
        Value: !Ref Stage
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: CrierDynamo
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Action: "dynamodb:*"
            Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${CapiStreamName}_${App}-${Mode}-${Stage}
      - PolicyName: DataAccess
        PolicyDocument:
           Version: 2012-10-17
           Statement:
             Effect: Allow
             Action:
             - dynamodb:DescribeTable
             - dynamodb:GetItem
             - dynamodb:GetRecords
             - dynamodb:PutItem
             - dynamodb:Query
             - dynamodb:UpdateItem
             Resource: !GetAtt UnattachedAtomsTable.Arn
      - PolicyName: DeployablesAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Action:
             - s3:ListBucket
             - s3:GetObject
            Resource:
            - arn:aws:s3:::gnm-multimedia-rr-deployables
            - arn:aws:s3:::gnm-multimedia-rr-deployables/*
            - arn:aws:s3:::gnm-multimedia-deployables
            - arn:aws:s3:::gnm-multimedia-deployables/newrelic*
      - PolicyName: RoleAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Action:
            - sts:AssumeRole
            Resource: !Ref CapiRole
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - !Ref InstanceRole
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Instance security group for launchdetector
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - SourceSecurityGroupId: !GetAtt LoadBalancerSG.GroupId
          FromPort: 9000
          ToPort: 9000
          IpProtocol: tcp
        - CidrIp: !Ref OfficeIpRange
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
  UnattachedAtomsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userEmail
          AttributeType: S
        - AttributeName: dateCreated
          AttributeType: S
        - AttributeName: dummy
          AttributeType: S
      KeySchema:
        - AttributeName: userEmail
          KeyType: HASH
        - AttributeName: dateCreated
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: dateIndex
          KeySchema:
          - AttributeName: dummy
            KeyType: HASH
          - AttributeName: dateCreated
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            WriteCapacityUnits: 1
            ReadCapacityUnits: 1
      ProvisionedThroughput:
        WriteCapacityUnits: 1
        ReadCapacityUnits: 1
      TableName: !Sub LaunchDetectorUnattachedAtoms-${Stage}-v7
      Tags:
        - Key: App
          Value: !Sub ${App}
        - Key: Stack
          Value: !Sub ${Stack}
        - Key: Stage
          Value: !Sub ${Stage}
  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPair
      SecurityGroups:
      - !Ref InstanceSecurityGroup
      UserData: !Base64
        "Fn::Sub": |
          #!/bin/bash -e

          mkdir -p /tmp/install
          aws s3 sync s3://gnm-multimedia-rr-deployables/${Stack}/${Stage}/${App} /tmp/install

          declare -x MOST_RECENT_PACKAGE=`ls -Frt /tmp/install/*.deb | grep "[^/]$" | tail -n 1`
          echo Going to install $MOST_RECENT_PACKAGE
          dpkg --install "${!MOST_RECENT_PACKAGE}"

          aws s3 cp s3://gnm-multimedia-deployables/newrelic-java-3.43.0.zip /tmp
          mkdir -p /usr/share/multimedia-launchdetector-v3/newrelic/logs
          chown multimedia-launchdetector-v3 /usr/share/multimedia-launchdetector-v3/newrelic/logs
          cd /usr/share/multimedia-launchdetector-v3
          unzip /tmp/newrelic-java-3.43.0.zip

          cat > /usr/share/multimedia-launchdetector-v3/newrelic/newrelic.yml << EOF
          common: &default_settings
            license_key: '${NewRelicLicense}'
            agent_enabled: true
            app_name: Launch Detector (${Stage})
            log_level: info
            log_daily: true
            ssl: true

            labels:
              Stack: ${Stack}
              App: ${App}
              Stage: ${Stage}
          EOF

          mkdir -p /usr/share/multimedia-launchdetector-v3/conf
          cat > /usr/share/multimedia-launchdetector-v3/conf/application.conf << EOF
          capi_stream_name = "${CapiStreamName}"
          capi_role_name = "${CapiRole}"
          capi_mode = "${Mode}"

          app_name = "${App}"
          app_stack = "${Stack}"
          app_stage = "${Stage}"

          region = "${AWS::Region}"

          pluto_host = "${PlutoHost}"
          pluto_port = ${PlutoVidispinePort}
          pluto_user = ${PlutoUser}
          pluto_pass = ${PlutoPass}

          unattached_atoms_table = ${UnattachedAtomsTable}

          akka {
            http.client.connecting-timeout="1 second"
            log-dead-letters=0
            log-dead-letters-during-shutdown=off
          }

          EOF

          cat > /etc/default/multimedia-launchdetector-v3 << EOF
          JAVA_OPTS="-javaagent:/usr/share/multimedia-launchdetector-v3/newrelic/newrelic.jar -Dconfig.file=/usr/share/multimedia-launchdetector-v3/conf/application.conf"
          EOF

          systemctl restart multimedia-launchdetector-v3
  AutoScaleGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: "1"
      HealthCheckGracePeriod: 300
      HealthCheckType: ELB
      LaunchConfigurationName: !Ref LaunchConfig
      LoadBalancerNames:
      - !Ref LoadBalancer
      MaxSize: "8"
      MinSize: "1"
      Tags:
      - Key: App
        Value: !Ref App
        PropagateAtLaunch: true
      - Key: Stack
        Value: !Ref Stack
        PropagateAtLaunch: true
      - Key: Stage
        Value: !Ref Stage
        PropagateAtLaunch: true
      VPCZoneIdentifier: !Ref DeploySubnets
Outputs:
  LoadBalancerAddress:
    Value: !GetAtt LoadBalancer.DNSName